version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.01
    resource_class: large
    environment:
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dorg.gradle.daemon=false"
      _JAVA_OPTIONS: "-Xmx4g"
    
    steps:
      - checkout
      
      - run:
          name: Setup Gradle Properties
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" > ~/.gradle/gradle.properties
            echo "android.useAndroidX=true" >> ~/.gradle/gradle.properties
            
      - run:
          name: Build APK
          command: |
            chmod +x gradlew
            ./gradlew :TMessagesProj_App:assembleAfatRelease --stacktrace --no-daemon --info

      - store_artifacts:
          path: TMessagesProj_App/build/outputs/apk/afat/release
          destination: apk

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
